trigger:
  branches:
    include:
      - master
  paths:
    exclude:
      - 'renovate.json'
      - 'README.md'
      - 'jitpack.yml'
      - 'azure-pipelines-docker.yml'
      - '.whitesource'
      - '.travis.yml'
      - '.gitpod.*'
      - '.gitignore'
      - 'ci/README.md'
      - 'ci/diagrams/*'
      - '.vscode/*'
      - '.run/*'
      - '.devcontainer/*'

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-latest'
      osFam: 'linux'
    mac:
      imageName: 'macos-latest'
      osFam: 'mac'
    windows:
      imageName: 'windows-latest'
      osFam: 'windows'

pool:
  vmImage: $(imageName)

steps:
  - checkout: self
    submodules: recursive

  - task: Cache@2
    displayName: Gradle User Home Cache
    inputs:
      key: 'gradleUserHome | "$(Agent.OS)"'
      restoreKeys: gradleUserHome
      path: $(Agent.HomeDirectory)/.gradle

  - task: PowerShell@2
    displayName: Set mise cache paths
    inputs:
      filePath: $(Build.SourcesDirectory)/ci/set-cache-vars.ps1
      pwsh: true

  - task: Cache@2
    displayName: Cache mise (data and cache dirs)
    inputs:
      key: mise | $(Agent.OS) | $(Agent.OSArchitecture) | $(Build.SourcesDirectory)/mise.toml
      path: |
        $(MiseDataPath)
        $(MiseCachePath)

  - task: PowerShell@2
    displayName: Setup runtimes via mise and verify
    inputs:
      filePath: $(Build.SourcesDirectory)/ci/setup-mise-java.ps1
      pwsh: true

  - task: PowerShell@2
    displayName: "Gradle build : Android Library"
    inputs:
      filePath: $(Build.SourcesDirectory)/ci/gradle-build.ps1
      pwsh: true
    env:
      JAVA_HOME: $(JAVA_HOME)

  - task: PowerShell@2
    displayName: Stop Gradle daemon
    inputs:
      filePath: $(Build.SourcesDirectory)/ci/gradle-stop.ps1
      pwsh: true
