trigger:
  branches:
    include:
      - master
  paths:
    include:
      - '.gitpod.Dockerfile'

resources:
  - repo: self

stages:
  - stage: Build
    displayName: Build image
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: Docker@2
            displayName: Build an image
            inputs:
              command: build
              Dockerfile: '.gitpod.Dockerfile'
