trigger:
  branches:
    include:
      - master
  paths:
    exclude:
      - 'renovate.json'
      - 'README.md'
      - 'jitpack.yml'
      - 'azure-pipelines-docker.yml'
      - '.whitesource'
      - '.travis.yml'
      - '.gitpod.*'
      - '.gitignore'
      - '.vscode/*'
      - '.run/*'
      - '.devcontainer/*'

pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self
    submodules: recursive

  - task: Cache@2
    displayName: Gradle User Home Cache
    inputs:
      key: 'gradleUserHome | "$(Agent.OS)"'
      restoreKeys: gradleUserHome
      path: $(Agent.HomeDirectory)/.gradle

  - task: CmdLine@2
    displayName: Install mise
    inputs:
      script: |
        set -euo pipefail
        curl -fsSL https://mise.run | sh
        echo "##vso[task.prependpath]$HOME/.local/bin"
        echo "##vso[task.prependpath]$HOME/.local/share/mise/shims"
        mise --version

  - task: CmdLine@2
    displayName: Install Java via mise
    inputs:
      script: |
        set -euo pipefail
        mise install
        JHOME="$(mise where java)"
        if [ -z "$JHOME" ]; then
          echo "Failed to resolve JAVA_HOME via 'mise where java'" >&2
          exit 1
        fi
        echo "Detected JAVA_HOME: $JHOME"
        echo "##vso[task.setvariable variable=JAVA_HOME]$JHOME"
        echo "##vso[task.prependpath]$JHOME/bin"
        java -version
        javac -version

  - task: CmdLine@2
    displayName: Prepare mise cache dirs
    inputs:
      script: |
        mkdir -p $(Agent.HomeDirectory)/.local/share/mise
        mkdir -p $(Agent.HomeDirectory)/.cache/mise

  - task: Cache@2
    displayName: Cache mise data
    inputs:
      key: mise-data | $(Agent.OS) | $(Agent.OSArchitecture) | $(Build.SourcesDirectory)/mise.toml
      path: $(Agent.HomeDirectory)/.local/share/mise

  - task: Cache@2
    displayName: Cache mise cache
    inputs:
      key: mise-cache | $(Agent.OS) | $(Agent.OSArchitecture) | $(Build.SourcesDirectory)/mise.toml
      path: $(Agent.HomeDirectory)/.cache/mise

  - task: CmdLine@2
    displayName: "Guard: mise Java is active"
    inputs:
      script: |
        set -euo pipefail
        echo "Guard: verifying Java selection…"
        ACTIVE_JAVA="$(command -v java || true)"
        MISE_JAVA="$(mise which java || true)"
        echo "command -v java => $ACTIVE_JAVA"
        echo "mise which java => $MISE_JAVA"
        if [ -z "$ACTIVE_JAVA" ] || [ -z "$MISE_JAVA" ] || [ "$ACTIVE_JAVA" != "$MISE_JAVA" ]; then
          echo "Mismatch: shell java doesn't match mise java" >&2
          echo "PATH: $PATH"
          type -a java || true
          exit 1
        fi

        # Double-check JVM reports the same home as JAVA_HOME
        JVM_HOME="$(
          java -XshowSettings:properties -version 2>&1 | awk -F'= ' '/^ *java\.home =/ {print $2; exit}'
        )"
        echo "java.home => $JVM_HOME"
        if [ -z "$JAVA_HOME" ] || [ -z "$JVM_HOME" ] || [ "$JVM_HOME" != "$JAVA_HOME" ]; then
          echo "Mismatch: JVM java.home doesn't equal JAVA_HOME" >&2
          exit 1
        fi
        echo "Guard passed."

  - task: CmdLine@2
    displayName: "Gradle build : Android Library"
    inputs:
      script: ./gradlew build
    env:
      JAVA_HOME: $(JAVA_HOME)

  - task: CmdLine@2
    displayName: Stop Gradle Daemon
    inputs:
      script: ./gradlew --stop
