apply plugin: 'com.android.library'

android {

    namespace 'ndk.utils_android16'

    compileSdk 34
    useLibrary 'org.apache.http.legacy'

    defaultConfig {

        minSdkVersion 16
        targetSdkVersion 34

        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        useLibrary 'org.apache.http.legacy'
        multiDexEnabled true
    }

    buildTypes {

        release {

            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }

        staging {

            initWith release
            debuggable true
        }
    }

    // Specifies flavor dimension.
    flavorDimensions "relevence"
    productFlavors {

        // When building a variant that uses this flavor, the following configurations override those in the defaultConfig block.

        development {

            dimension "relevence"

            // To avoid using legacy multidex when building from the command line, set minSdkVersion to 21 or higher. When using Android Studio 2.3 or higher, the build automatically avoids legacy multidex when deploying to a device running API level 21 or higher—regardless of what you set as your minSdkVersion.
//            minSdkVersion 21

            // The following configuration limits the usage of mdpi screen-density resources.
            resConfigs "mdpi"
        }

        production {

            dimension "relevence"
            // If you've configured the defaultConfig block for the release version of your app, you can leave this block empty and Gradle uses configurations in the defaultConfig block instead. You still need to create this flavor. Otherwise, all variants use the "development" flavor configurations.
        }
    }

    variantFilter { variant ->

        def names = variant.flavors*.name

        // To check for a certain build type, use variant.buildType.name == "<buildType>"
        if (names.contains("development") && names.contains("release")) {

            // Gradle ignores any variants that satisfy the conditions above.
            setIgnore(true)
        }

        if (names.contains("production") && names.contains("debug")) {

            // Gradle ignores any variants that satisfy the conditions above.
            setIgnore(true)
        }

        if (names.contains("development") && names.contains("staging")) {

            // Gradle ignores any variants that satisfy the conditions above.
            setIgnore(true)
        }
    }

    lintOptions {

        checkReleaseBuilds false
        abortOnError false
    }
}

dependencies {

    implementation fileTree(include: ['*.jar'], dir: 'libs')

    implementation 'javax.inject:javax.inject:1'

    implementation 'org.apache.commons:commons-lang3:3.18.0'
    implementation 'com.itextpdf:itextpdf:5.5.13.4'
    implementation 'com.itextpdf:itext-pdfa:5.5.13.4'

    implementation 'com.github.Baneeishaque:CSnackBar:96a2d1a422'
    implementation 'de.codecrafters.tableview:tableview:2.8.1'
    implementation 'com.googlecode.libphonenumber:libphonenumber:9.0.12'
    implementation 'org.javatuples:javatuples:1.2'

    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'com.google.android.material:material:1.14.0'
    implementation 'androidx.legacy:legacy-support-core-utils:1.0.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'
    implementation 'androidx.multidex:multidex:2.0.1'

    implementation project(path: ':common14')
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}
